// @ts-nocheck
// Locale data for community_common.ts. Included before the shared runtime.

var COMMUNITY_LOCALE_CODE = "ja_JP";
var COMMUNITY_LOCALE_LABELS = {
  "cacheSettings": "設定",
  "browser": "ブラウザで開く",
  "go": "移動",
  "allBoards": "すべての掲示板",
  "home": "ホーム",
  "homeToggle": "ホームに追加",
  "homeRemove": "ホームから削除",
  "mediaToggle": "メディア表示",
  "galleryMode": "ギャラリーモード",
  "boardSettingsMenu": "掲示板",
  "boardSettingsTitle": "掲示板設定",
  "boardSync": "掲示板を取得",
  "openWithoutSync": "そのまま開く",
  "reorder": "並べ替え",
  "refresh": "更新",
  "save": "保存",
  "close": "閉じる",
  "add": "追加",
  "delete": "削除",
  "reset": "リセット",
  "cancel": "キャンセル",
  "confirm": "OK",
  "board": "掲示板",
  "boards": "掲示板",
  "boardId": "掲示板ID",
  "name": "名前",
  "boardUrl": "掲示板URL",
  "optionalName": "名前 (任意)",
  "settings": "設定",
  "cacheTtlMinutes": "キャッシュTTL (分)",
  "showCacheSnackbar": "キャッシュ通知を表示",
  "categoryTwoChar": "短いカテゴリ表示",
  "galleryColumns": "ギャラリー列数",
  "customGroup": "ユーザー追加",
  "syncedGroup": "同期済み",
  "defaultGroup": "基本",
  "category": "カテゴリ",
  "emptyBoards": "掲示板がありません。",
  "visibleSuffix": "表示",
  "group": "グループ",
  "groups": "グループ"
};
var COMMUNITY_LOCALE_MESSAGES = {
  "cachedNotice": "Cached {age} ago, {remaining} remaining.",
  "categoryShortcut": "Category shortcut",
  "cacheDialogMessage": "Change the settings.",
  "goDialogMessage": "Enter a URL to open. Full URLs and /paths are supported.",
  "urlRequired": "Enter a URL.",
  "authCompleteInBrowser": "Complete authentication in the browser.",
  "boardIdNameDialog": "Enter a board ID and name.",
  "boardUrlDialog": "Enter a board URL. Leave the name empty to use it automatically.",
  "boardAddTitle": "Add Board",
  "boardDeleteTitle": "Delete Boards",
  "boardDeleteMessage": "Checked boards are kept. Unchecked boards will be deleted.",
  "noDeletableBoards": "There are no boards that can be deleted.",
  "noCachedBoardsPrompt": "No cached full board list exists. Run {sync} now?",
  "noBoardsToFetch": "No boards to fetch.",
  "fetchedBoards": "Fetched {count} boards.",
  "boardReactivated": "Board is visible again: {title}",
  "boardAdded": "Board added: {title}",
  "boardAddedShort": "Board added.",
  "boardReactivatedShort": "Board is visible again.",
  "boardDeleted": "Board deleted.",
  "boardShown": "Board is now visible.",
  "boardHidden": "Board is now hidden.",
  "boardNotFound": "Board not found.",
  "boardStateFailed": "Could not change board state.",
  "boardAddToHome": "{title} added to Home.",
  "boardRemoveFromHome": "{title} removed from Home.",
  "groupShortcutRemoveFailed": "Could not remove the group Home shortcut.",
  "groupAddToHome": "{title} group added to Home.",
  "groupRemoveFromHome": "{title} group removed from Home.",
  "settingsSaved": "Settings saved.",
  "settingsReset": "Settings reset.",
  "cacheSettingsSaved": "Cache settings saved.",
  "cacheSettingsReset": "Cache settings reset.",
  "cacheTtlMin": "Cache TTL must be at least 1 minute.",
  "galleryColumnsMin": "Gallery columns must be at least 1.",
  "orderSaved": "Order saved.",
  "reorderEnabled": "Reorder enabled.",
  "reorderDisabled": "Reorder disabled.",
  "refreshDone": "Refresh complete.",
  "refreshPathNotFound": "Could not find a path to refresh.",
  "noMorePosts": "No more posts to load.",
  "nextPageFailed": "Could not load the next page.",
  "duplicateSkipped": "Skipped duplicate posts.",
  "routeLoadFailed": "Could not load the route.",
  "loginRequired": "Login is required.",
  "postContentFailed": "Could not load the post body.",
  "unsupportedSiteUrl": "This site URL is not supported by this extension.",
  "boardIdNameRequired": "Enter both board ID and name.",
  "boardUrlBuildFailed": "Could not create a board URL.",
  "boardSaveFailed": "Could not save board information.",
  "boardUrlRequired": "Enter a board URL.",
  "boardUrlUnrecognized": "Could not recognize the board URL.",
  "customBoardExists": "This board already exists.",
  "removedBoards": "Deleted {count} boards.",
  "cookieSavedButBlocked": "Cookies were saved, but access is still blocked.",
  "cookieFetchFailed": "Could not get authentication cookies.",
  "authNotComplete": "Authentication is not complete yet. Continue in the browser."
};
var COMMUNITY_MORE_COUNT_TEXT = "他 {count}件";
var COMMUNITY_DURATION_TEXT = {
  "minuteSecond": "{minutes}m {seconds}s",
  "second": "{seconds}s"
};
var COMMUNITY_BOARD_KEYWORD_PATTERN = "forum|forums|board|boards|community|category|categories|group|groups|topic|topics|tag|tags|gallery|galleries|club|clubs|channel|channels|section|sections|掲示板|カテゴリ|グループ";
var COMMUNITY_EXCLUDED_BOARD_GROUP_PATTERN = "";
